#!/usr/bin/python
import sys
kernel_name="Linux"
node_name="ots"
kernel_release="3.10.0-1062.9.1.el7.x86_64"
kernel_version="#1 SMP Thu Dec 5 14:44:59 CST 2019"
machine="x86_64"
processor="x86_64"
hardware_platform="x86_64"
operating_system="GNU/Linux"
param_map = {
  "-s" : kernel_name,
  "-n" : node_name,
  "-r" : kernel_release,
  "-v" : kernel_version,
  "-m" : machine,
  "-p" : processor,
  "-i" : hardware_platform,
  "-o" : operating_system,
  "-a" : "%s %s %s %s %s %s %s %s" % (kernel_name,node_name,kernel_release,kernel_version,machine,processor,hardware_platform,operating_system)
}

output=""
user_args=sys.argv
if len(user_args) == 1:
    user_args=["-s"]

for arg in user_args:
    if param_map.has_key(arg):
        output+=" "  + param_map[arg]

print output.strip()
